textObj(tickers_file = r'C:\Users\Owner\500_tickers.txt')
textObj.createDroptbFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')
textObj = textconverter()
textObj.createDroptbFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')
textObj.queryRow(tickers_file = r'C:\Users\Owner\500_tickers.txt')
textObj.querytbRowFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
textObj = textconverter()
from textconverter import textconverter
textObj = textconverter()
textObj.querytbRowFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')
textObj.createDroptbFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
textObj.querytbRowFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')
textObj.createDroptbFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
textObj.doublequoteTicker(tickers_file = r'C:\Users\Owner\deleteme.txt')
textObj.doublequoteTicker('ASC')
textObj.querytbRowFile(tickers_file = r'C:\Users\Owner\deleteme.txt')
textObj.createDroptbFile(tickers_file = r'C:\Users\Owner\deleteme.txt')
textObj.createDroptbFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')
textObj.querytbRowFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
textObj.querytbRowFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')
textObj.createDroptbFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
textObj.querytbRowFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')
textObj.createDroptbFile(tickers_file = r'C:\Users\Owner\500_tickers.txt')

## ---(Sat Aug 15 10:06:40 2020)---
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
from textconverter import textconverter
txtObj = textconverter()
print(txtObj.prefixMySQLtableName('RWT/LN'))
print(txtObj.getTickerFromtb('tb_RWT_LN'))
print(txtObj.getTickerFromTb('tb_RWT_LN'))
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
txtObj.querytbRowFileMySQL(r'C:\Users\Owner\deleteme.txt')
txtObj.querytbRowFileMySQL(tickers_file = r'C:\Users\Owner\deleteme.txt')
print('?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?'.replace('?', '%s')
print('?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?'.replace('?', '%s'))
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
txtObj.createDroptbFileMySQL(tickers_file = r'C:\Users\Owner\deleteme.txt')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDApi.py')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDApi.py')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
history
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDApi.py')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
txtObj.createDroptbFileMySQL(tickers_file = r'C:\Users\Owner\500_tickers.txt')
txtObj = textconverter()
txtObj.createDroptbFileMySQL(tickers_file = r'C:\Users\Owner\500_tickers.txt')
txtObj.querytbRowFileMySQL
(tickers_file = r'C:\Users\Owner\500_tickers.txt')
txtObj.querytbRowFileMySQL(tickers_file = r'C:\Users\Owner\500_tickers.txt')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
runcell(0, 'C:/Users/Owner/.spyder-py3/untitled1.py')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
runcell(0, 'C:/Users/Owner/.spyder-py3/tempConsole.py')
runcell(0, 'C:/Users/Owner/.spyder-py3/TDSession_TestRun.py')
hsitory 
history
txtObj = textconverter()
txtObj.path(r'C:\Owner\Tickers\myfile.txt')
print(txtObj.path(r'C:\Owner\Tickers\myfile.txt'))
txtObj.maketickerfile(tickers_file = r'C:\Users\Owner\Tickers_lists\3000_tickers.txt', new_file = 'tickerlist3.txt', size = 3, group_number = 5)
txtObj.maketickerfile(tickers_file = r'C:\Users\Owner\Tickers_lists\3000_tickers.txt', new_file = 'C:\Users\Owner\Tickers_lists\tickerlist3.txt', size = 3, group_number = 5)
txtObj.maketickerfile(tickers_file = r'C:\Users\Owner\Tickers_lists\3000_tickers.txt', new_file = r'C:\Users\Owner\Tickers_lists\tickerlist3.txt', size = 3, group_number = 5)
txtObj.maketickerfile(tickers_file = r'C:\Users\Owner\Tickers_lists\3000_tickers.txt', new_file = r'C:\Users\Owner\Tickers_lists\tickerlist3.txt', size = 7, group_number = 0)
txtObj.maketickerfile(tickers_file = r'C:\Users\Owner\Tickers_lists\3000_tickers.txt', new_file = r'C:\Users\Owner\Tickers_lists\tickerlist1.txt', size = 7, group_number = 1)
runcell(0, 'C:/Users/Owner/.spyder-py3/tempConsole.py')
check_output("dir C:", shell=True)
runfile('C:/Users/Owner/.spyder-py3/tempConsole.py', wdir='C:/Users/Owner/.spyder-py3')
check_output("dir C:", shell=True)
runcell(0, 'C:/Users/Owner/.spyder-py3/tempConsole.py')
check_output("dir C:\\", shell=True).decode()
check_output("dir C:\\Users\\Owner\\", shell=True).decode()
runcell(0, 'C:/Users/Owner/.spyder-py3/tempConsole.py')
txtObj.createDroptbFileSQLServer(tickers_file = r'C:\Users\Owner\Tickers_lists\tickerlist1.txt')
txtObj.querytbRowFileSQLServer(tickers_file = r'C:\Users\Owner\Tickers_lists\tickerlist1.txt')
runcell(0, 'C:/Users/Owner/.spyder-py3/tempConsole.py')

## ---(Sun Aug 16 11:42:33 2020)---
runcell(0, 'C:/Users/Owner/.spyder-py3/tempConsole.py')
import os
from os import path
os.path.getmtime('C:\\Users\\Owner\\.spyder-py3\\.Tuong_TDA_accessToken_cache.txt')
datetime.datetime()
date.datetime()
datetime()
time.time()
import time
time.time()
timeObj = timeConverter()
from timeConverter import timeConverter
timeObj = timeConverter()
timeObj.file_age('C:\\Users\\Owner\\.spyder-py3\\.Tuong_TDA_accessToken_cache.txt')
runcell(0, 'C:/Users/Owner/.spyder-py3/tempConsole.py')